---
- name: Prometheus node exporter deployment
  hosts: all
  become: True
  remote_user: ansible
  gather_facts: True

  roles:
      - role: dreamlines.prometheus-node-exporter
        prometheus_node_exporter_version: 0.16.0
        prometheus_node_exporter_enabled_collectors:
          - conntrack
          - cpu
          - diskstats
          - entropy
          - filefd
          - filesystem
          - loadavg
          - mdadm
          - meminfo
          - netdev
          - netstat
          - stat
          - textfile
          - time
          - vmstat
        prometheus_node_exporter_config_flags:
          'web.listen-address': '0.0.0.0:7100'
          'log.level': 'info'
